### ISSUE TITLE
🐛 New Bug:

### ISSUE THREAD

**Issue by sagaronin** [WasiqB/ultra-reporter-app#52]
### ❓ What is the bug?

Not able to generate report by uploading testng-result.xml file

### 📃 Steps to reproduce the bug

create simple selenium-java project using maven
write one simple test and run it using surefire plugin by adding below tag in surefire plugin
<suiteXmlFiles>
            <suiteXmlFile>testng.xml</suiteXmlFile>
          </suiteXmlFiles>
         

### ✅ Expected Behavior

shold be able to generate report

### ❌ Actual Behavior

getting date not supported error

**Comment by sagaronin** [comment]
I am using latest version of -
Selenium 4.25
testNG
maven
IDE used - VS code

**Comment by WasiqB** [comment]
@sagaronin , please share your `testng-results.xml` file

**Comment by sagaronin** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-12T13:09:07 EDT" name="Practice Suite" finished-at="2024-10-12T13:09:32 EDT" duration-ms="24928">
    <groups>
    </groups>
    <test started-at="2024-10-12T13:09:07 EDT" name="Test Basics 1" finished-at="2024-10-12T13:09:32 EDT" duration-ms="24928">
      <class name="org.example.InvokeBrowser">
        <test-method is-config="true" signature="setup()[pri:0, instance:org.example.InvokeBrowser@59505b48]" started-at="2024-10-12T13:09:07 EDT" name="setup" finished-at="2024-10-12T13:09:11 EDT" duration-ms="4136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method signature="AssertLogoPresent()[pri:0, instance:org.example.InvokeBrowser@59505b48]" started-at="2024-10-12T13:09:11 EDT" name="AssertLogoPresent" finished-at="2024-10-12T13:09:11 EDT" duration-ms="26" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"css selector","selector":".qb\-logo"}
  (Session info: chrome=129.0.6668.90)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [65f721f5433eb027cb30cab6b3c54532, findElement {using=class name, value=qb-logo}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.90, chrome: {chromedriverVersion: 129.0.6668.100 (cf58cba358d..., userDataDir: C:\Users\sagar\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:20649}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:20649/devtoo..., se:cdpVersion: 129.0.6668.90, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 65f721f5433eb027cb30cab6b3c54532]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":".qb\-logo"}
  (Session info: chrome=129.0.6668.90)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [65f721f5433eb027cb30cab6b3c54532, findElement {using=class name, value=qb-logo}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.90, chrome: {chromedriverVersion: 129.0.6668.100 (cf58cba358d..., userDataDir: C:\Users\sagar\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:20649}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:20649/devtoo..., se:cdpVersion: 129.0.6668.90, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 65f721f5433eb027cb30cab6b3c54532
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.example.InvokeBrowser.AssertLogoPresent(InvokeBrowser.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> 
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.example.InvokeBrowser@59505b48]" started-at="2024-10-12T13:09:11 EDT" name="tearDown" finished-at="2024-10-12T13:09:12 EDT" duration-ms="229" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> 
      </class> 
      <class name="org.example.RelativeLocatorExample">
        <test-method is-config="true" signature="setup()[pri:0, instance:org.example.RelativeLocatorExample@f0c8a99]" started-at="2024-10-12T13:09:12 EDT" name="setup" finished-at="2024-10-12T13:09:16 EDT" duration-ms="4731" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method signature="RelativeLocatorStrategyExample(java.lang.String,java.lang.String)[pri:0, instance:org.example.RelativeLocatorExample@f0c8a99]" started-at="2024-10-12T13:09:16 EDT" name="RelativeLocatorStrategyExample" finished-at="2024-10-12T13:09:16 EDT" duration-ms="14" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test@123]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"css selector","selector":"#qb\-username"}
  (Session info: chrome=129.0.6668.90)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [2b4f9ef4653e239eff270e47bb1c5077, findElement {using=id, value=qb-username}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.90, chrome: {chromedriverVersion: 129.0.6668.100 (cf58cba358d..., userDataDir: C:\Users\sagar\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:20675}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:20675/devtoo..., se:cdpVersion: 129.0.6668.90, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 2b4f9ef4653e239eff270e47bb1c5077]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#qb\-username"}
  (Session info: chrome=129.0.6668.90)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [2b4f9ef4653e239eff270e47bb1c5077, findElement {using=id, value=qb-username}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.90, chrome: {chromedriverVersion: 129.0.6668.100 (cf58cba358d..., userDataDir: C:\Users\sagar\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:20675}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:20675/devtoo..., se:cdpVersion: 129.0.6668.90, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 2b4f9ef4653e239eff270e47bb1c5077
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.example.RelativeLocatorExample.RelativeLocatorStrategyExample(RelativeLocatorExample.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> 
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.example.RelativeLocatorExample@f0c8a99]" started-at="2024-10-12T13:09:16 EDT" name="tearDown" finished-at="2024-10-12T13:09:17 EDT" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> 
      </class> 
      <class name="org.example.MockGeoLocation">
        <test-method is-config="true" signature="setup()[pri:0, instance:org.example.MockGeoLocation@740cae06]" started-at="2024-10-12T13:09:17 EDT" name="setup" finished-at="2024-10-12T13:09:18 EDT" duration-ms="1465" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method signature="mockGeoLocation_ExecuteCdpCommand()[pri:0, instance:org.example.MockGeoLocation@740cae06]" started-at="2024-10-12T13:09:18 EDT" name="mockGeoLocation_ExecuteCdpCommand" finished-at="2024-10-12T13:09:22 EDT" duration-ms="4426" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.example.MockGeoLocation@740cae06]" started-at="2024-10-12T13:09:22 EDT" name="tearDown" finished-at="2024-10-12T13:09:23 EDT" duration-ms="866" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method is-config="true" signature="setup()[pri:0, instance:org.example.MockGeoLocation@740cae06]" started-at="2024-10-12T13:09:23 EDT" name="setup" finished-at="2024-10-12T13:09:25 EDT" duration-ms="1676" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method signature="mockGeoLocation_devTools()[pri:0, instance:org.example.MockGeoLocation@740cae06]" started-at="2024-10-12T13:09:25 EDT" name="mockGeoLocation_devTools" finished-at="2024-10-12T13:09:30 EDT" duration-ms="5399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> 
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.example.MockGeoLocation@740cae06]" started-at="2024-10-12T13:09:30 EDT" name="tearDown" finished-at="2024-10-12T13:09:32 EDT" duration-ms="1741" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> 
      </class> 
    </test> 
  </suite> 
</testng-results>
`

**Comment by WasiqB** [comment]
@sagaronin , I used the file content you provided, saved it in a XML file, and uploaded the same in the reporter and it loaded successfully.

See the screenshot below for your test results:

![image](https://github.com/user-attachments/assets/351dea28-b460-41d4-9532-5a4928db82b7)

Are you using this URL to upload the results: https://ultra-reporter-app.vercel.app/

**Comment by sagaronin** [comment]
@WasiqB I was using this URL earlier to upload the file - https://ultra-reporter-app.vercel.app/
However, I can also see the report being generated now. You can mark this Bug as resolved.
